name: CS7641
dependencies:
  - python=3.6
  - numpy == 1.15.1
  - scipy == 1.1.0
  - scikit-learn == 0.20.0
  - pandas == 0.23.4
  - matplotlib == 2.2.3
  - seaborn == 0.9.0
  - pip
  - pip:
    - xlrd==0.9.0
    - scikit-optimize==0.5.2